[package]
name = "untitled-rustgame"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.17"
leafwing-input-manager = "0.19"
toml = "0.9.8"
serde = { version = "1.0.228", features = ["derive"] }

[profile.dev.package."*"]
opt-level = 3
